apiVersion: apps/v1   
kind: Deployment   
metadata:   
  labels:   
    app: multitool   
  name: backend   
  namespace: default  
spec:   
  replicas: 1   
  selector:   
    matchLabels:   
      app: multitool   
  template:   
    metadata:   
      labels:   
        app: multitool   
    spec:   
      - image: praqma/network-multitool:alpine-extra   
        imagePullPolicy: IfNotPresent   
        name: backend   
        env:   
          - name: HTTP_PORT   
            value: "9000"      