apiVersion: apps/v1   
kind: Deployment   
metadata:   
  labels:   
    app: nginx   
  name: frontend   
  namespace: default  
spec:   
  replicas: 1   
  selector:   
    matchLabels:   
      app: nginx   
  template:   
    metadata:   
      labels:   
        app: nginx   
    spec:   
      containers:   
      - image: nginx:1.20   
        imagePullPolicy: IfNotPresent   
        name: frontend   
          value: "8000"      