apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  ports:
    - name: web
      port: 9000
    - name: postgresql-db
      port: 5432
  selector:
    app: nginx
  type: ClusterIP
