apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  ports:
    - name: web
      port: 8000
    - name: backend
      port: 9000
  selector:
    app: nginx
  type: ClusterIP
